# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create package keycloak
        run: mvn clean install
      - name: Rename package

        run: mv ./target/connector-keycloak-*.jar ./target/inalogy-keycloak-${{ github.ref_name }}.jar

      - name: Upload push-keycloak
        uses: actions/upload-artifact@v4
        with:
          name: Inalogy
          path: ./target/inalogy-keycloak-${{ github.ref_name }}.jar

      - name: Create push-keycloak release
        id: create_release_push-keycloak
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: keycloak-${{ github.ref_name }}
          release_name: Release Push KEYCLOAK ${{ github.ref_name }}
          body: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset-push-keycloak
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_push-keycloak.outputs.upload_url }} 
          asset_path: ./target/inalogy-keycloak-${{ github.ref_name }}.jar
          asset_name: inalogy-keycloak-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive